apiVersion: v1
kind: Service
metadata:
  name: dterm-service
  namespace: default
spec:
  type: NodePort
  selector:
    app: dterm
  ports:
    - protocol: TCP
      port: 30000
      targetPort: 3000
      nodePort: 30000
