[main]
listen = ":3000"

[log]
path = ""
level = "trace"
max_size = 100
max_age = 2
max_backups = 10

[mysql]
host = "127.0.0.1"
port = 3306
database = "dterm"
user = "root"
password = ""

[redis]
addr = "127.0.0.1"
db = 0
password = ""
