[main]
listen = ":3000"
data_dir = "./"

[log]
path = ""
level = "trace"
max_size = 100
max_age = 2
max_backups = 10

[easy]
schema = "http"
domain = "127.0.0.1:10081"
api_check_token = "/api_check_token"

# [mysql]
# host = "127.0.0.1"
# port = 3306
# database = "dterm"
# user = "root"
# password = ""

# [redis]
# addr = "127.0.0.1"
# db = 0
# password = ""
